[theme]

# Primary accent for interactive elements
primaryColor = '#FFBD2F'

# Background color for the main content area
backgroundColor = '#ffffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFBD2F'

# Color used for almost all text
textColor = '#646464'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"